version: '3.6'
services:
  synth:
    build: .
    image: synth
    environment:
      - PURPOSE=synth
    env_file:
      - three_musketeers.env
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock #Needed so a docker container can be run from inside a docker container
      - ~/.aws/:/root/.aws:ro

  bootstrap:
    image: synth
    environment:
      - PURPOSE=local-cdk-bootstrap
    env_file:
      - three_musketeers.env
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock #Needed so a docker container can be run from inside a docker container
      - ~/.aws/:/root/.aws:ro

  npm-install:
    image: synth
    environment:
      - PURPOSE=npm-install
    env_file:
      - three_musketeers.env
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock #Needed so a docker container can be run from inside a docker container
      - ~/.aws/:/root/.aws:ro

  deploy:
    image: synth
    environment:
      - PURPOSE=local-cdk-deploy
    env_file:
      - three_musketeers.env
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock #Needed so a docker container can be run from inside a docker container
      - ~/.aws/:/root/.aws:ro

  destroy:
    image: synth
    environment:
      - PURPOSE=local-cdk-destroy
    env_file:
      - three_musketeers.env
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock #Needed so a docker container can be run from inside a docker container
      - ~/.aws/:/root/.aws:ro

  diff:
    image: synth
    environment:
      - PURPOSE=local-cdk-diff
    env_file:
      - three_musketeers.env
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock #Needed so a docker container can be run from inside a docker container
      - ~/.aws/:/root/.aws:ro